### Ping-pong
GET http://127.0.0.1:8080/ping HTTP/1.1
content-type: application/json

### List all questions
GET http://127.0.0.1:8080/api/v0/questions HTTP/1.1
content-type: application/json

### Add a question
POST http://127.0.0.1:8080/api/v0/questions HTTP/1.1
content-type: application/json

{
    "Text": "Is this a good question?"
}

### Delete all question
DELETE http://127.0.0.1:8080/api/v0/questions HTTP/1.1
content-type: application/json

### Up-vote a question
POST http://127.0.0.1:8080/api/v0/questions/6/up-vote HTTP/1.1
content-type: application/json